#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-1 -d I II III IV V 
bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc config border_radius 18

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#383C36"
bspc config focused_border_color "#6200F6"
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a "Microsoft Teams - Preview" desktop='^3'
bspc rule -a REAPER desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Skype pseudo_tiled=on

$HOME/.config/polybar/launch.sh

